name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          docker pull ghcr.io/apache/incubator-linkis/linkis:dev-1.3.0-2000027b9e5ffa8a0172ad4b15dee0b582f801da
