name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: docker
        run: |
          docker pull ghcr.io/apache/incubator-linkis/linkis:dev-1.3.0-2000027b9e5ffa8a0172ad4b15dee0b582f801da
          docker save -o image.tar ghcr.io/apache/incubator-linkis/linkis:dev-1.3.0-2000027b9e5ffa8a0172ad4b15dee0b582f801da
          ls -a ./ 

      - name: scheduled commit contributor
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
